version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TERM=xterm-256color
    volumes:
      - .:/usr/src/kmcc
      - $HOME/.vimrc:/root/.vimrc
